# Generated by Django 5.1.1 on 2024-10-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhonemicAwareness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phoneme", models.CharField(max_length=5)),
                ("word", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="phoneme_images/")),
                ("sound", models.FileField(upload_to="phoneme_sounds/")),
            ],
        ),
    ]
