# Generated by Django 5.1.1 on 2024-10-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_phoneticsymbol_delete_phonemicawareness"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhonemeExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phoneme", models.CharField(max_length=10)),
                ("example_word", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="phoneticsymbol",
            name="phoneme_examples",
            field=models.ManyToManyField(to="myapp.phonemeexample"),
        ),
    ]
