# Generated by Django 5.1.1 on 2024-10-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_remove_phoneticsymbol_phoneme_examples_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneticRepresentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phoneme", models.CharField(max_length=10)),
                ("word", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="phonemes/images/")),
                (
                    "sound_phoneme",
                    models.FileField(blank=True, upload_to="phonemes/sounds/"),
                ),
                (
                    "sound_word",
                    models.FileField(blank=True, upload_to="phonemes/sounds/"),
                ),
            ],
        ),
    ]
