# Generated by Django 3.2.25 on 2024-10-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(max_length=100)),
                ('example_sentence', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('audio_word', models.FileField(blank=True, upload_to='audio/words/')),
                ('audio_pronunciation', models.FileField(blank=True, upload_to='audio/pronunciation/')),
                ('audio_example', models.FileField(blank=True, upload_to='audio/example/')),
            ],
        ),
        migrations.CreateModel(
            name='Foodswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('corrected_word', models.CharField(blank=True, max_length=100)),
                ('pronunciation', models.CharField(blank=True, max_length=100)),
                ('example_sentence', models.TextField()),
                ('corrected_sentence', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('audio_word', models.FileField(blank=True, upload_to='audio/words/')),
                ('audio_pronunciation', models.FileField(blank=True, upload_to='audio/pronunciation/')),
                ('audio_example', models.FileField(blank=True, upload_to='audio/example/')),
                ('corrected_paragraph', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phoneme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('audio_file', models.FileField(upload_to='phoneme_audios')),
            ],
        ),
        migrations.CreateModel(
            name='schoolwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(max_length=100)),
                ('example_sentence', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('audio_word', models.FileField(blank=True, upload_to='audio/words/')),
                ('audio_pronunciation', models.FileField(blank=True, upload_to='audio/pronunciation/')),
                ('audio_example', models.FileField(blank=True, upload_to='audio/example/')),
            ],
        ),
        migrations.CreateModel(
            name='SightWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='sight_word_audios')),
            ],
        ),
        migrations.CreateModel(
            name='SightWord1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='sight_word_audios_level_2')),
            ],
        ),
        migrations.CreateModel(
            name='SightWord2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='sight_word_audios_level_3')),
            ],
        ),
        migrations.CreateModel(
            name='SightWord4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='sight_word_audios_level_4')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pronunciation_text', models.CharField(max_length=100)),
                ('example_sentence_text', models.TextField()),
                ('corrected_sentence_text', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('audio_word', models.FileField(blank=True, null=True, upload_to='audio/words/')),
                ('audio_pronunciation', models.FileField(blank=True, null=True, upload_to='audio/pronunciation/')),
                ('audio_example', models.FileField(blank=True, null=True, upload_to='audio/example/')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyWord22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(blank=True, max_length=100)),
                ('example_sentence', models.TextField(blank=True)),
                ('corrected_sentence', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='vocab_images/')),
                ('audio_word', models.FileField(blank=True, upload_to='vocab_audio/')),
                ('audio_pronunciation', models.FileField(blank=True, upload_to='vocab_audio/')),
                ('audio_example', models.FileField(blank=True, upload_to='vocab_audio/')),
                ('audio_corrected_sentence', models.FileField(blank=True, upload_to='vocab_audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
    ]
