# Generated by Django 5.0.6 on 2024-07-25 10:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(max_length=100)),
                ('example_sentence', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('audio_word', models.FileField(blank=True, upload_to='audio/words/')),
                ('audio_pronunciation', models.FileField(blank=True, upload_to='audio/pronunciation/')),
                ('audio_example', models.FileField(blank=True, upload_to='audio/example/')),
            ],
        ),
        migrations.CreateModel(
            name='Foodswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('corrected_word', models.CharField(blank=True, max_length=100)),
                ('pronunciation', models.CharField(blank=True, max_length=100)),
                ('example_sentence', models.TextField()),
                ('corrected_sentence', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('audio_word', models.FileField(blank=True, upload_to='audio/words/')),
                ('audio_pronunciation', models.FileField(blank=True, upload_to='audio/pronunciation/')),
                ('audio_example', models.FileField(blank=True, upload_to='audio/example/')),
                ('corrected_paragraph', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phoneme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('audio_file', models.FileField(upload_to='phoneme_audios')),
            ],
        ),
        migrations.CreateModel(
            name='schoolwords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(max_length=100)),
                ('example_sentence', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('audio_word', models.FileField(blank=True, upload_to='audio/words/')),
                ('audio_pronunciation', models.FileField(blank=True, upload_to='audio/pronunciation/')),
                ('audio_example', models.FileField(blank=True, upload_to='audio/example/')),
            ],
        ),
        migrations.CreateModel(
            name='SightWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='sight_word_audios')),
            ],
        ),
        migrations.CreateModel(
            name='SightWord1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='sight_word_audios_level_2')),
            ],
        ),
        migrations.CreateModel(
            name='SightWord2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='sight_word_audios_level_3')),
            ],
        ),
        migrations.CreateModel(
            name='SightWord4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='sight_word_audios_level_4')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(max_length=100)),
                ('example_sentence', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('audio_word', models.FileField(blank=True, upload_to='audio/words/')),
                ('audio_pronunciation', models.FileField(blank=True, upload_to='audio/pronunciation/')),
                ('audio_example', models.FileField(blank=True, upload_to='audio/example/')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyWord22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(blank=True, max_length=100)),
                ('example_sentence', models.TextField(blank=True)),
                ('corrected_sentence', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='vocab_images/')),
                ('audio_word', models.FileField(blank=True, upload_to='vocab_audio/')),
                ('audio_pronunciation', models.FileField(blank=True, upload_to='vocab_audio/')),
                ('audio_example', models.FileField(blank=True, upload_to='vocab_audio/')),
                ('audio_corrected_sentence', models.FileField(blank=True, upload_to='vocab_audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_code', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('delivery_location', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('email',), name='unique_email'),
        ),
    ]
