# Generated by Django 5.0.6 on 2024-06-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_phoneme_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sightword',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='sightword',
            name='audio_file',
            field=models.FileField(default='exit', upload_to='sightword_audios/'),
            preserve_default=False,
        ),
    ]
