# Generated by Django 5.0.6 on 2024-06-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_sightword_audio_url_sightword_audio_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SightWord',
        ),
    ]
