# Generated by Django 5.0.6 on 2024-06-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_sightword'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightWord1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('audio_file', models.FileField(upload_to='sight_word_audios_level_2')),
            ],
        ),
    ]
