# Generated by Django 5.0.6 on 2024-06-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_sightword2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneme',
            name='name',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='sightword',
            name='word',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sightword1',
            name='word',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sightword2',
            name='word',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
