# Generated by Django 5.0.6 on 2024-06-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_phoneme_name_alter_sightword_word_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightWord4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('audio_file', models.FileField(upload_to='sight_word_audios_level_4')),
            ],
        ),
    ]
