# Generated by Django 5.0.6 on 2024-06-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_vocabularyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyword',
            name='category',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
