# Generated by Django 5.0.6 on 2024-07-01 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_vocabularyword_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VocabularyWord',
        ),
    ]
