# Generated by Django 5.0.6 on 2024-07-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_animalwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(max_length=100)),
                ('example_sentence', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('audio_word', models.FileField(blank=True, upload_to='audio/words/')),
                ('audio_pronunciation', models.FileField(blank=True, upload_to='audio/pronunciation/')),
                ('audio_example', models.FileField(blank=True, upload_to='audio/example/')),
            ],
        ),
    ]
