# Generated by Django 5.0.6 on 2024-07-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_schoolwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodswords',
            name='corrected_paragraph',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foodswords',
            name='corrected_sentence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foodswords',
            name='corrected_word',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
