# Generated by Django 5.0.6 on 2024-07-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_foodswords_corrected_paragraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodswords',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
