# Generated by Django 5.0.6 on 2024-07-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_foodswords_pronunciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodswords',
            name='pronunciation_correct',
            field=models.BooleanField(default=True),
        ),
    ]
