# Generated by Django 5.0.6 on 2024-07-16 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_foodswords_pronunciation_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodswords',
            name='pronunciation_correct',
        ),
    ]
