# Generated by Django 5.0.6 on 2024-07-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_foodswords_pronunciation_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyWord2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(max_length=100)),
                ('example_sentence', models.TextField()),
                ('corrected_sentence', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('audio_word', models.FileField(blank=True, null=True, upload_to='audio/words/')),
                ('audio_pronunciation', models.FileField(blank=True, null=True, upload_to='audio/pronunciation/')),
                ('audio_example', models.FileField(blank=True, null=True, upload_to='audio/example/')),
                ('audio_corrected_sentence', models.FileField(blank=True, null=True, upload_to='audio/corrected/')),
            ],
        ),
    ]
