# Generated by Django 5.0.6 on 2024-07-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_vocabularyword2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularyword2',
            name='audio_corrected_sentence',
            field=models.FileField(blank=True, default=2, upload_to='vocab_audio/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vocabularyword2',
            name='audio_example',
            field=models.FileField(blank=True, upload_to='vocab_audio/'),
        ),
        migrations.AlterField(
            model_name='vocabularyword2',
            name='audio_pronunciation',
            field=models.FileField(blank=True, upload_to='vocab_audio/'),
        ),
        migrations.AlterField(
            model_name='vocabularyword2',
            name='audio_word',
            field=models.FileField(blank=True, default='exit', upload_to='vocab_audio/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vocabularyword2',
            name='corrected_sentence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vocabularyword2',
            name='example_sentence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vocabularyword2',
            name='image',
            field=models.ImageField(blank=True, upload_to='vocab_images/'),
        ),
        migrations.AlterField(
            model_name='vocabularyword2',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
