# Generated by Django 5.0.6 on 2024-07-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_vocabularyword2_audio_corrected_sentence_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VocabularyWord2',
            new_name='VocabularyWord22',
        ),
    ]
